/*
 * Statistics Service
 * Statistics Service
 *
 * OpenAPI spec version: 9.0.000.21.527
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.genesys.internal.common.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
