/*
 * Statistics Service
 * Statistics Service
 *
 * OpenAPI spec version: 9.0.000.00.402
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.genesys.internal.statistics.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PeekedStatisticValue
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-13T00:07:04.391Z")
public class PeekedStatisticValue {
  @SerializedName("name")
  private String name = null;

  @SerializedName("objectId")
  private String objectId = null;

  @SerializedName("objectType")
  private String objectType = null;

  @SerializedName("timestamp")
  private Long timestamp = null;

  @SerializedName("value")
  private Object value = null;

  public PeekedStatisticValue name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the statistic.
   * @return name
  **/
  @ApiModelProperty(value = "The name of the statistic.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PeekedStatisticValue objectId(String objectId) {
    this.objectId = objectId;
    return this;
  }

   /**
   * The ID of the object (in Stat Server&#39;s terms).
   * @return objectId
  **/
  @ApiModelProperty(value = "The ID of the object (in Stat Server's terms).")
  public String getObjectId() {
    return objectId;
  }

  public void setObjectId(String objectId) {
    this.objectId = objectId;
  }

  public PeekedStatisticValue objectType(String objectType) {
    this.objectType = objectType;
    return this;
  }

   /**
   * The type of object.
   * @return objectType
  **/
  @ApiModelProperty(value = "The type of object.")
  public String getObjectType() {
    return objectType;
  }

  public void setObjectType(String objectType) {
    this.objectType = objectType;
  }

  public PeekedStatisticValue timestamp(Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * The timestamp when the statistic value was generated (provided by Stat Server).
   * @return timestamp
  **/
  @ApiModelProperty(value = "The timestamp when the statistic value was generated (provided by Stat Server).")
  public Long getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }

  public PeekedStatisticValue value(Object value) {
    this.value = value;
    return this;
  }

   /**
   * The value of the statistic. Its structure reflects the structure of the Stat Server message.
   * @return value
  **/
  @ApiModelProperty(value = "The value of the statistic. Its structure reflects the structure of the Stat Server message.")
  public Object getValue() {
    return value;
  }

  public void setValue(Object value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PeekedStatisticValue peekedStatisticValue = (PeekedStatisticValue) o;
    return Objects.equals(this.name, peekedStatisticValue.name) &&
        Objects.equals(this.objectId, peekedStatisticValue.objectId) &&
        Objects.equals(this.objectType, peekedStatisticValue.objectType) &&
        Objects.equals(this.timestamp, peekedStatisticValue.timestamp) &&
        Objects.equals(this.value, peekedStatisticValue.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, objectId, objectType, timestamp, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PeekedStatisticValue {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    objectId: ").append(toIndentedString(objectId)).append("\n");
    sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

